# Copyright 2025 Sophie Lund
#
# This file is part of Forge.
#
# Forge is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Forge is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Forge. If not, see
# <https://www.gnu.org/licenses/>.

site_name: Forge

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - content.code.copy

extra_css:
  - custom.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - admonition

nav:
  - Intro: index.md
  - Language:
      - Planning: language/planning.md
  - Reference:
      - Message codes: reference/message-codes.md
  - For compiler developers:
      - Tutorial:
          - Defining a syntax tree: for-compiler-developers/tutorial/defining-a-syntax-tree.md
          - Debug formatting: for-compiler-developers/tutorial/debug-formatting.md
          - Well formed validation: for-compiler-developers/tutorial/well-formed-validation.md
      - Reference:
          - Coding standards: for-compiler-developers/reference/coding-standards.md
          - Naming convention: for-compiler-developers/reference/naming-convention.md
